services:
  postgres:
    image: postgres:15.13
    container_name: sfit-redis-postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sfit-db-2016
      POSTGRES_DB: sfit-backend-go
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: sfit-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sfit-backend-go
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    restart: on-failure

volumes:
  pgdata:
  redisdata: