### Đăng ký tài khoản
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "testuser@example.com",
    "password": "TestPassword123@"
}

###

### Đăng nhập
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "TestPassword123"
}

###

### Đăng xuất
POST http://localhost:8080/auth/logout
Authorization: Bearer <your_access_token>

###

### Làm mới token
POST http://localhost:8080/auth/refresh
Content-Type: application/json

### lấy tag
GET http://localhost:8080/tags
Accept: application/json

### Tạo ban mới
POST http://localhost:8080/teams
Content-Type: application/json

{
  "name": "Ban Học Tập",
  "description": "Thành viên ban phải tham gia học tập"
}

### Cập nhật thông tin ban
PUT http://localhost:8080/teams
Content-Type: application/json

{
  "id": "6c48f131-15aa-499a-bd4e-a9d4d1c9f1aa",
  "name": "Ban Học Tập Update",
  "description": "Thông tin ban học tập đã cập nhật"
}

