### tạo mới event (thiếu tag, sắp xếp theo)
POST http://localhost:8080/event
Content-Type: application/json
{
  "title": "Summer Festival",
  "type": "Event",
  "description": "A fun summer gathering with music and food",
  "priority": 2,
  "locaion": "Central Park",
  "max_people": 150,
  "agency": "City Events",
  "status": "UPCOMING",
  "begin_at": "2025-08-15T10:00:00Z",
  "end_at": "2025-08-15T18:00:00Z"
}

### lấy chi tiết sự kiện (duyệt)
GET http://localhost:8080/event/{9a7d21bb-d136-4324-901e-aad613988863} 

### lấy danh sách event (thiếu registed: boolean)
GET http://localhost:8080/event/list

### xóa event (duyệt)
DELETE http://localhost:8080/event/{9a7d21bb-d136-4324-901e-aad613988863}

### điểm danh (lỗi)
POST http://localhost:8080/event/subscribe


