### Lấy danh sách task
GET http://localhost:8080/tasks?page=1&pageSize=10&event_id=00000000-0000-0000-0000-000000000000&name=
Accept: application/json

###

### Lấy chi tiết một task
GET http://localhost:8080/tasks/5d0d1fb6-f7b2-4a74-a93a-e857104cde5e
Accept: application/json

###

### Tạo mới một task
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "name": "Support Admin",
    "description": "The Support",
    "startTime:" : "2025-08-12T22:00:00+07:00",
    "event_id": "7a781645-b88f-4046-8710-1ca62f9735ec",
    "dateline" : "2025-08-14T22:00:00+07:00"
}

###

### Cập nhật một task
PUT http://localhost:8080/tasks/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
    "name": "Support Admin",
    "description": "The Support",
    "startTime:" : "2025-08-12T22:00:00+07:00",
    "event_id": "7a781645-b88f-4046-8710-1ca62f9735ec",
    "dateline" : "2025-08-14T22:00:00+07:00"
}

###

### Xóa một task
DELETE http://localhost:8080/tasks/00000000-0000-0000-0000-000000000000
Accept: application/json