### Update User Profile
### Nhập Token sau Authorization: Brearer ...
PUT http://localhost:8080/user-profile/update
Content-Type: application/json
Authorization: Bearer <Token>


{
  "full_name": "Nobita Shizuka",
  "class_name": "CNTT4",
  "khoa": "65",
  "phone": "0123456789",
  "introduction": "Tôi là sinh viên năm 2",
  "social_link": {
    "github": "https://github.com/nguyenvana",
    "facebook": "https://facebook.com/shizuka"
  }
}

###CREATE USER PROFILE
POST http://localhost:8080/user-profile/
Content-Type: application/json
Authorization: Bearer <Token>


{
  "full_name": "Nobita Doraemon",
  "class_name": "CNTT4",
  "khoa": "65",
  "phone": "0123456789",
  "introduction": "Tôi là sinh viên năm 1",
  "completed_course": 2,
  "joined_event": 2,
  "completed_task": 2,
  "social_link": {
    "github": "https://github.com/nguyenvana",
    "facebook": "https://facebook.com/shizuka"
  }
}

###DELETE USER
DELETE http://localhost:8080/user-profile/{user_id}


###GET USER PROFILE
GET http://localhost:8080/user-profile/{user_id}
